// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCignFulRik-_IT-Y-LyY4yMYMYzZfH5lU',
    appId: '1:881263447241:android:3a2db87442ac123cded118',
    messagingSenderId: '881263447241',
    projectId: 'vchat-5d495',
    storageBucket: 'vchat-5d495.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPkSzrvl2Jdt9YgKtkD27xQ8rKomhpzpc',
    appId: '1:881263447241:ios:e999aac18d1eec5dded118',
    messagingSenderId: '881263447241',
    projectId: 'vchat-5d495',
    storageBucket: 'vchat-5d495.appspot.com',
    androidClientId: '881263447241-pghvja49mr5m7j0003t4uag3it56ck2q.apps.googleusercontent.com',
    iosClientId: '881263447241-msniq9jpp80o66tii90td4h1g3dgh5hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.jitsy',
  );
}
